version: '3.3'
services:
  object-detector:
    image: ${APP_NAME}
    command: /usr/bin/objdetector /models/server.pem
    depends_on:
      - acap_dl-models
      - inference-server
    ipc: host
    environment:
      - INFERENCE_HOST=unix:///tmp/acap-runtime.sock
      - INFERENCE_PORT=0
      - MODEL_PATH=${MODEL_PATH}
      - OBJECT_LIST_PATH=/models/coco_labels.txt
    volumes:
      - /usr/lib/libvdostream.so.1:/usr/lib/libvdostream.so.1
      - acap_dl-models:/models:ro
      - /var/run/dbus:/var/run/dbus:rw
      - inference-server:/tmp

  inference-server:
      image: ${INFERENCE_SERVER_IMAGE}
      logging:
        driver: "json-file"
        options:
          max-file: "5"
          max-size: "100k"
      entrypoint: ["/opt/app/acap_runtime/acapruntime", "-o", "-m", "${MODEL_PATH}", "-j", "${INFERENCE_CHIP}", "-c", "/models/server.pem", "-k", "/models/server.key"]
      depends_on:
        - acap_dl-models
      ipc: host
      volumes:
        - /usr/acap-root/lib:/host/lib
        - acap_dl-models:/models:ro
        - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
        - /run/parhand/parhandsocket:/run/parhand/parhandsocket
        - /usr/lib:/usr/lib
        - /usr/bin:/usr/bin
        - inference-server:/tmp

  acap_dl-models:
    image: ${MODEL_NAME}
    volumes:
      - acap_dl-models:/models

volumes:
  acap_dl-models: {}
  inference-server: {}
